apiVersion: v1
data:
  db-name: DB_NAME
  db-password: DB_PASSWORD
  db-username: DB_USERNAME
  root-password: DB_ROOT_PWD
kind: Secret
metadata:
  name: {{ include "expense-tracker-config.fullname" . }}-mysql-secret
  namespace: hillel-expense-tracker
type: Opaque