{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "expense-tracker-ingress.fullname" . }}
  labels:
    {{- include "expense-tracker-ingress.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - http:
        paths:
          - backend:
              service:
                name: expense-tracker-backend
                port:
                  number: 8080
            path: /tracker/api
            pathType: Prefix

    {{- end }}
{{- end }}
