server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /tracker/api

logging:
  level:
    org.springframework.boot: INFO
    ua.ithillel.expensetracker.controller: DEBUG
    ua.ithillel.expensetracker: DEBUG