server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /tracker/api

logging:
  level:
    org.springframework.boot: INFO
    ua.ithillel.expensetracker.controller: DEBUG
    ua.ithillel.expensetracker: INFO

management:
  server:
    port: 8081
    address: localhost
  endpoints:
  endpoint:
    beans:
      access: read_only
    metrics:
      access: unrestricted
