services:
  expense-tracker-backend:
    depends_on:
      - expense-tracker-mysql
    build: ../../
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - expense-tracker-backend:/tmp
    env_file:
      - ../../.env


  expense-tracker-mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ../../.env
    volumes:
      - expense-tracker-mysql:/var/lib/mysql

volumes:
  expense-tracker-mysql:
  expense-tracker-backend:
