apiVersion: v1
kind: Service
metadata:
  name: {{ include "expense-tracker-mysql.fullname" . }}
  labels:
    {{- include "expense-tracker-mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: mysql
  selector:
    {{- include "expense-tracker-mysql.selectorLabels" . | nindent 4 }}
