name: Sonar pipeline

on:
  push
#  push:
#    branches:
#      - main

jobs:

  sonar-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Run Sonarqube report
        run : ./mvnw clean test sonar:sonar \
          -Dsonar.projectKey=Hillel-Expense-Tracker \
          -Dsonar.projectName='Hillel Expense Tracker' \
          -Dsonar.host.url=${{ secrets.SONAR_URL }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}